<a href="https://colab.research.google.com/github/yasmim-petri/marketing-analytics/blob/main/Ifood.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Avaliação das campanhas de marketing do Ifood

In [15]:
import pandas as pd

Carregamento do DataSet

In [16]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Ifood/iFood.xlsx", sheet_name="iFood")

Leituras iniciais

In [17]:
df.shape
df.head()

,Index,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp2,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmpOverall,Complain,Age,Customer_Days,marital_status,education
0,1001,58138,0,0,58,635,88,546,172,88,...,0,0,0,0,0,0,63,2822,Single,Graduation
1,1002,46344,1,1,38,11,1,6,2,1,...,0,0,0,0,0,0,66,2272,Single,Graduation
2,1003,71613,0,0,26,426,49,127,111,21,...,0,0,0,0,0,0,55,2471,Together,Graduation
3,1004,26646,1,0,26,11,4,20,10,3,...,0,0,0,0,0,0,36,2298,Together,Graduation
4,1005,58293,1,0,94,173,43,118,46,27,...,0,0,0,0,0,0,39,2320,Married,PHD

In [18]:
def visualiza_df(df):
    '''
        Exibe informações básicas do DataFrame que está sendo observado
    '''
    #Formato do DF
    print('\033[31m Formato:\033[0m')
    print(f'{df.shape[0] :,} linhas e {df.shape[1]} colunas.')

    # Valores ausentes
    print(f'{'=' * 50}')
    print('\033[31m Valores ausentes:\033[0m')
    print(df.isnull().sum())

    # Duplicatas
    print(f'{'=' * 50}')
    print('\033[31m Duplicatas: \033[0m')
    print(df.duplicated().sum())

    # Tipos de dados
    print(f'{'=' * 50}')
    print('\033[31m Tipos de dados: \033[0m')
    print(df.dtypes)

    # Visualização dados brutos
    print(f'{'=' * 50}')
    print('\033[31m Pré-visualização dos dados: \033[0m')
    df.head(5)

    return df

In [19]:
visualiza_df(df)

 Formato:
2,205 linhas e 29 colunas.
==================================================
 Valores ausentes:
Index                  0
Income                 0
Kidhome                0
Teenhome               0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntRegularProds        0
MntGoldProds           0
MntTotal               0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp1           0
AcceptedCmp2           0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmpOverall     0
Complain               0
Age                    0
Customer_Days          0
marital_status         0
education              0
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
Index                   int64
Income                  int64
Kidhome                 int64
Teenhome                int64
Recency                 int64
MntWines                int64
MntFruits               int64
MntMeatProducts         int64
MntFishProducts         int64
MntSweetProducts        int64
MntRegularProds         int64
MntGoldProds            int64
MntTotal                int64
NumDealsPurchases       int64
NumWebPurchases         int64
NumCatalogPurchases     int64
NumStorePurchases       int64
NumWebVisitsMonth       int64
AcceptedCmp1            int64
AcceptedCmp2            int64
AcceptedCmp3            int64
AcceptedCmp4            int64
AcceptedCmp5            int64
AcceptedCmpOverall      int64
Complain                int64
Age                     int64
Customer_Days           int64
marital_status         object
education              object
dtype: object
==================================================
 Pré-visualização dos dados:

,Index,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp2,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmpOverall,Complain,Age,Customer_Days,marital_status,education
0,1001,58138,0,0,58,635,88,546,172,88,...,0,0,0,0,0,0,63,2822,Single,Graduation
1,1002,46344,1,1,38,11,1,6,2,1,...,0,0,0,0,0,0,66,2272,Single,Graduation
2,1003,71613,0,0,26,426,49,127,111,21,...,0,0,0,0,0,0,55,2471,Together,Graduation
3,1004,26646,1,0,26,11,4,20,10,3,...,0,0,0,0,0,0,36,2298,Together,Graduation
4,1005,58293,1,0,94,173,43,118,46,27,...,0,0,0,0,0,0,39,2320,Married,PHD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,3201,61223,0,1,46,709,43,182,42,118,...,0,0,0,0,0,0,53,2540,Married,Graduation
2201,3202,64014,2,1,56,406,0,30,0,0,...,0,0,0,0,1,0,74,2178,Together,PHD
2202,3203,56981,0,0,91,908,48,217,32,12,...,0,0,1,0,1,0,39,2314,Divorced,Graduation
2203,3204,69245,0,1,8,428,30,214,80,30,...,0,0,0,0,0,0,64,2315,Together,Master
2204,3205,52869,1,1,40,84,3,61,2,1,...,0,0,0,0,0,0,66,2781,Married,PHD

Duas colunas de texto: Situação civil e escolaridade

In [20]:
df['marital_status'].value_counts()

marital_status
Married     854
Together    568
Single      477
Divorced    230
Widow        76
Name: count, dtype: int64

In [21]:
df['education'].value_counts()

education
Graduation    1113
PHD            476
Master         364
2n Cycle       198
Basic           54
Name: count, dtype: int64

Como escolaridade é categórioca ordinal podemos substituir ela pelo "nível" que representa.

In [22]:
df['education'] = df['education'].replace({"Graduation":3,"PHD":5,"Master":4,"2n Cycle":2,"Basic":1})
df['education'].value_counts()

/tmp/ipykernel_2440/1930057349.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['education'] = df['education'].replace({"Graduation":3,"PHD":5,"Master":4,"2n Cycle":2,"Basic":1})

education
3    1113
5     476
4     364
2     198
1      54
Name: count, dtype: int64